"""add risk_score and extracted identifier columns

Revision ID: 06c7dad78bad
Revises: 3bcde8ba8d9c
Create Date: 2026-08-30 22:56:34.904710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c7dad78bad'
down_revision: Union[str, Sequence[str], None] = '3bcde8ba8d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_pan_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extracted_account_number', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_extracted_account_number'), ['extracted_account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_extracted_pan_number'), ['extracted_pan_number'], unique=False)

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_column('risk_score')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_extracted_pan_number'))
        batch_op.drop_index(batch_op.f('ix_documents_extracted_account_number'))
        batch_op.drop_column('extracted_account_number')
        batch_op.drop_column('extracted_pan_number')

    # ### end Alembic commands ###
